version: 2

sources:
  - name: Demo
    database: mimetic-fulcrum-341607
    schema: Demo
    tables:
      - name: Goalscorers

models:
  - name: stg_goalscorers
    columns:
      - name: player_name
        tests:
          - not_null
      - name: date
        tests:
          - not_null